[project]
name = "animator"
version = "0.1.0"
requires-python = ">=3.10"
description = "Live animations from text prompts"
readme = "README.md"
dependencies = [
   "openai",
   "flask",
   "openai",
   "werkzeug",
   "manim",
   "latex",
]
